baseURL = 'https://blog.grishk.in/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

[params]
user = "max"
hostname = "grishk.in"
published = true
readingTime = false
math = false

  [params.author]
    name = "Maxim Grishkin"
    email = ""

[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "posts"
  # [[menu.header]]
  #   name = "about"
  #   weight = 2
  #   url = "about"

# math
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
